### ISSUE TITLE
I can't use it. Please hep me

### ISSUE THREAD

**Issue by zjt20210918** [BhaskarPanja93/Adfly-View-Bot-Client#15]
Hello, can you do a simple video tutorial, I think it is more intuitive, thank you very much

**Comment by Dec1lent** [comment]
I can make a video tutorial when I get home. Also we are currently working on making the proxy checker work more effieciently and also expanding to Linkvertise.
Read more in the [Discussion](https://github.com/BhaskarPanja93/Adfly-View-Bot-Client/discussions/9)
If you have any questions ask there.
@zjt20210918

**Comment by zjt18263412280** [comment]
Thank you, the project is doing very well, really want to master it immediately
