### ISSUE TITLE
No Push Ads on Ghost Spectre

### ISSUE THREAD

**Issue by BhaskarPanja93** [BhaskarPanja93/Adfly-View-Bot-Client#2]
@Dec1lent   I tried Win10 pro ghost spectre, it same as Windows server, just the extra benefit, Server consumes 3GB of extra storage space, but on the other hand i am having a massive issue, idk why but i am rarely receiving Push Ads on the ghost spectre. extremely rare to get an ad, any cure to this maybe you know?

**Comment by Dec1lent** [comment]
Thats weird, I thought it was a problem on all windows vm's, but turns out its just ghost spectre. Maybe its telemetry but I dont think so. It could be alot of different things since ghost have changed almost everything.

**Comment by BhaskarPanja93** [comment]
Well, as far as I could go, for some reason, Chrome is auto-changing its "show ads" and "allow popups" toggles, and secondly, ghost spectre isnt allowing, because it basically desnt support it, but i am wondering then why is it working "sometimes". As of now I am sticking to the Windows server VMs (v2.1 as in GDrive), and things seem to work normally. Ghost spectre and windows server are built the same in terms of CPU and Memory efficiency, well server is faster, and ghost spectre consumes less storage. Will have to investigate more into the not receiving Push ads problem, then shift to Ghost probably on the next iteration if things start working.

**Comment by Dec1lent** [comment]
In a few hours the push ads will update, I think that I might have found something.

**Comment by BhaskarPanja93** [comment]
If by cpm you mean Clicks per minute, thats true, i have intentionally reduced my CPM so that AdFly doesnt recognise as spam. Also my bot focuses more on Push ads which dont really need a lot of Clicks, rather just 1 ad view(the full skip ad process) and then its just mere chrome usage, and the Push ads keep coming, so yeah, but in terms of earning, they are quite the same. Also to increase your CPM what you can do is clone the VirtualMachine and run multiple instances of them parallelly.

And also you found "Something"? anything that might help?

**Comment by Dec1lent** [comment]
I just dug a little deeper in the useragent leak, but ended dead. All of Winscripes proxies gets detected for me, can I just use a rotating proxy on the host machine and make the vm use the same ip as the host? And also I earned 0,03 cents on my own bot with undetected-chromedriver and earned 0,01 cents on yours (I had only run it on one vm and only for a few hours.)

**Comment by BhaskarPanja93** [comment]
Ok first of all, AdFly updates earnings on a 2 day delay, you gotta wait 2 days to know the actual value you earned from push ads. I earn 0.7 - 1 USD per day (per account per VM)
Secondly i dont think Windscribe is the issue, I have been earning since January, using my code and its still working, while a new account that my friend made , got banned in 2 days. Not pretty sure what the issue is. 
Also about using proxies, i am not sure if, and how proxies work. Let me find something and then I will change accordingly. If you know how to use proxies, one thing you can do is run the proxy in your Host pc, the VM will use the same proxy and IP automatically, (But it will also connect to Winscribe VPN as of now, tell me if you want me to remove this VPN job).
And also regarding getting banned, I am starting to think one needs to go slower the first month after you create your adfly account, and then you can run the code maybe all day and multiple VMs only after you get your first monthly payment. 
On asking AdFly guys why accounts are getting banned, they just say "Push ads were manipulated", not pretty sure what this means.
