### ISSUE TITLE
VM not showing up on website

### ISSUE THREAD

**Issue by BhaskarPanja93** [BhaskarPanja93/Adfly-View-Bot-Client#5]
There has been a server side bug causing VMs to not show up on the website, this does not differ performance of the VM in any way. This is caused most probably for using multiple user_vm_connections. Currently working on a fix.

**Comment by Dec1lent** [comment]
Was getting all weirded out why I was logged out today, glad that you are working on it :D and also on vm restart I get logged out of Windscripe and cant login again before i reset the whole vm.

**Comment by BhaskarPanja93** [comment]
@Dec1lent Ok 1st of all. I checked you were using too many VMs at once. It poses the risk of getting banned because 10VMs is a lot. Also you cant login the same windscibe account in multiple accounts because they dont allow that. 1 VM = 1 windscibe account.
Also i silently updated the server without publicly posting anything, the new code reduced Client to server Response time by 50-60percent, which basically means you will get views 2-3x faster now, also made some small changes so that if any particular server crashes, the backup endpoints will be used, this particular thing is causing the VMs to not show up on the website and sometimes showing 0ms response time which is impossible, I am fixing it by tomorrow.
Also the VMs will restart on their own, its just part of the process dont worry about that also windscibe and client_uname_check should remember your credentials. If anything goes wrong, just restart the VM as of now.

**Comment by Dec1lent** [comment]
Got it, even though Windscripe says that they allowed unlimited amount of devices, they might think that im sharing my account with too many people and thats why it only works before the vms restarts :D

**Comment by BhaskarPanja93** [comment]
True, just create multiple Windscribe accounts, using fake emails, and then login to the VMs with those accounts.

**Comment by BhaskarPanja93** [comment]
Problem solved, test succeded. No extra user input required.
